- name: Install Clickhouse
  hosts: clickhouse
  tags: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Get clickhouse distrib
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "/tmp/{{ item }}_{{ clickhouse_version }}.deb"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse common static
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "/tmp/clickhouse-common-static_{{ clickhouse_version }}.deb"
            mode: "0644"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "/tmp/{{ item }}"
      with_items:
        - "clickhouse-common-static_{{ clickhouse_version }}.deb"
        - "clickhouse-client_{{ clickhouse_version }}.deb"
        - "clickhouse-server_{{ clickhouse_version }}.deb"
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Wait for clickhouse-server to get ready
      ansible.builtin.pause:
        seconds: 30

    - name: Create database
      become: true
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tags: vector
  handlers:
    - name: Restart Vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted

  tasks:
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
        dest: /tmp/vector-{{ vector_version }}-amd64.deb
        mode: "0644"

    - name: Install Vector packages
      become: true
      ansible.builtin.apt:
        deb: /tmp/vector-{{ vector_version }}-amd64.deb
      notify: Restart Vector service

    - name: Create Vector config directory
      become: true
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        mode: '0755'

    - name: Deploy Vector configuration
      become: true
      ansible.builtin.template:
        src: vector.yml.j2
        dest: /etc/vector/vector.yml
        mode: '0644'
      notify: Restart Vector service
